### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by osgee** [roylez/yuncli#3]
分享文件和得到分享文件的下载链接

**Comment by roylez** [comment]
首先这个脚本用的是百度pcs API，而分享链接这个，并不在pcs API里面，所以我一开始就没有做。确实我见过其他的一些项目实现了这个功能，不过他们用的不是单单pcs API，还有分析网页http请求得到的一些其他的百度API endpoint，我觉得太复杂了，而且没个保证，没准哪天百度就改了，所以就一直没有去弄。

另一方面，我现在在墙外，我自己都不能用这个登录百度云了，提示要我输入密保手机的验证码，所以也没办法继续进行这个项目的开发。

欢迎有需求的人接手或者clone继续开发。

**Comment by osgee** [comment]
出现了认证的bug
度娘云 /apps/bypy > auto_server
度娘云 /apps/bypy > quota
OpenSSL::SSL::SSLError: hostname "c2.pcs.baidu.com" does not match the server certificate
/usr/share/ruby/openssl/ssl.rb:178:in `post_connection_check'
/usr/share/ruby/net/http.rb:920:in`connect'
/usr/share/ruby/net/http.rb:862:in `do_start'
/usr/share/ruby/net/http.rb:851:in`start'
/usr/share/ruby/net/http.rb:1367:in `request'
./yuncli:85:in`request'
./yuncli:301:in `request_json'
./yuncli:222:in`run'
./yuncli:539:in `api_run'
./yuncli:420:in`quota'
./yuncli:679:in `quota'
./yuncli:803:in`dispatch_command'
./yuncli:621:in `main_loop'
./yuncli:887:in`<main>'

**Comment by roylez** [comment]
这个我在 f22b4c1 里修复。百度又改了API endpoint。
